package practicafinal2;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xp
 */
public class interfaz extends javax.swing.JFrame {
    
    
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
         try {
            gc.conect.setAutoCommit(false);

            Statement sta = gc.conect.createStatement();

            String query = "SELECT * FROM cliente ";

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();      

            this.jTable2.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
      
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        TITULO = new javax.swing.JLabel();
        nombre_cliente = new javax.swing.JTextField();
        apellido_cliente = new javax.swing.JTextField();
        Dni_cliente = new javax.swing.JTextField();
        telefono_cliente = new javax.swing.JTextField();
        direecion_cliente = new javax.swing.JTextField();
        sexo_cliente = new javax.swing.JTextField();
        nombre_empleado = new javax.swing.JTextField();
        apellido_empleado = new javax.swing.JTextField();
        Dni_empleado = new javax.swing.JTextField();
        telefono_empleado = new javax.swing.JTextField();
        direccion_empleado = new javax.swing.JTextField();
        puesto_empleado = new javax.swing.JTextField();
        alta3 = new javax.swing.JLabel();
        alta4 = new javax.swing.JLabel();
        dni1_eliminado = new javax.swing.JTextField();
        dni2_eliminado = new javax.swing.JTextField();
        Eliminar1 = new javax.swing.JButton();
        Eliminar2 = new javax.swing.JButton();
        consulta_cliente = new javax.swing.JButton();
        consulta_empleado = new javax.swing.JButton();
        consulta_tiendas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        alta_cliente = new javax.swing.JButton();
        alta_empleado = new javax.swing.JButton();
        tienda_cliente = new javax.swing.JTextField();
        tienda_empleado = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        modificar3 = new javax.swing.JTextField();
        modificar2 = new javax.swing.JTextField();
        modificar4 = new javax.swing.JTextField();
        modificar5 = new javax.swing.JTextField();
        modificar6 = new javax.swing.JTextField();
        modificar7 = new javax.swing.JTextField();
        modificar1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        coloca_datos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        jLabel3.setText("     APELLIDOS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TITULO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TITULO.setForeground(new java.awt.Color(153, 0, 0));
        TITULO.setText("TIENDA DE ROPA");

        nombre_cliente.setText("Nombre");
        nombre_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombre_clienteMouseClicked(evt);
            }
        });

        apellido_cliente.setText("Apellidos");
        apellido_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellido_clienteMouseClicked(evt);
            }
        });

        Dni_cliente.setText("DNI");
        Dni_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dni_clienteMouseClicked(evt);
            }
        });

        telefono_cliente.setText("Telefono");
        telefono_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefono_clienteMouseClicked(evt);
            }
        });

        direecion_cliente.setText("Direccion");
        direecion_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direecion_clienteMouseClicked(evt);
            }
        });

        sexo_cliente.setText("Sexo");
        sexo_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexo_clienteMouseClicked(evt);
            }
        });

        nombre_empleado.setText("Nombre");
        nombre_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombre_empleadoMouseClicked(evt);
            }
        });

        apellido_empleado.setText("Apellidos");
        apellido_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apellido_empleadoMouseClicked(evt);
            }
        });

        Dni_empleado.setText("DNI");
        Dni_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dni_empleadoMouseClicked(evt);
            }
        });

        telefono_empleado.setText("Telefono");
        telefono_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefono_empleadoMouseClicked(evt);
            }
        });

        direccion_empleado.setText("Direccion");
        direccion_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccion_empleadoMouseClicked(evt);
            }
        });

        puesto_empleado.setText("Puesto");
        puesto_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puesto_empleadoMouseClicked(evt);
            }
        });

        alta3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alta3.setForeground(new java.awt.Color(153, 0, 0));
        alta3.setText("ELIMINAR CLIENTE:");

        alta4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alta4.setForeground(new java.awt.Color(153, 0, 0));
        alta4.setText("ELIMINAR EMPLEADO:");

        dni1_eliminado.setText("DNI");
        dni1_eliminado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dni1_eliminadoMouseClicked(evt);
            }
        });

        dni2_eliminado.setText("DNI");
        dni2_eliminado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dni2_eliminadoMouseClicked(evt);
            }
        });

        Eliminar1.setBackground(new java.awt.Color(255, 102, 102));
        Eliminar1.setText("ELIMINAR");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        Eliminar2.setBackground(new java.awt.Color(255, 102, 102));
        Eliminar2.setText("ELIMINAR");
        Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar2ActionPerformed(evt);
            }
        });

        consulta_cliente.setBackground(new java.awt.Color(0, 0, 0));
        consulta_cliente.setForeground(new java.awt.Color(255, 255, 255));
        consulta_cliente.setText("CONSULTAR CLIENTES");
        consulta_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_clienteActionPerformed(evt);
            }
        });

        consulta_empleado.setBackground(new java.awt.Color(0, 0, 0));
        consulta_empleado.setForeground(new java.awt.Color(255, 255, 255));
        consulta_empleado.setText("CONSULTAR EMPLEADOS");
        consulta_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_empleadoActionPerformed(evt);
            }
        });

        consulta_tiendas.setBackground(new java.awt.Color(0, 0, 0));
        consulta_tiendas.setForeground(new java.awt.Color(255, 255, 255));
        consulta_tiendas.setText("CONSULTAR TIENDAS");
        consulta_tiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_tiendasActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        alta_cliente.setBackground(new java.awt.Color(255, 153, 153));
        alta_cliente.setText("DAR DE ALTA CLIENTE");
        alta_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_clienteActionPerformed(evt);
            }
        });

        alta_empleado.setBackground(new java.awt.Color(255, 153, 153));
        alta_empleado.setText("DAR DE ALTA EMPLEADO");
        alta_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_empleadoActionPerformed(evt);
            }
        });

        tienda_cliente.setText("Numero Tienda");
        tienda_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tienda_clienteMouseClicked(evt);
            }
        });

        tienda_empleado.setText("Numero Tienda");
        tienda_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tienda_empleadoMouseClicked(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(255, 102, 102));
        modificar.setText("MODIFICAR");
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });

        jLabel1.setText("        NOMBRE");

        jLabel2.setText("     APELLIDOS");

        jLabel4.setText("    Nº TIENDA");

        jLabel5.setText("           DNI");

        jLabel6.setText("    TELEFONO");

        jLabel7.setText("  DIRECCION");

        coloca_datos.setText("COLOCAR DATOS DE LA TABLA");
        coloca_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coloca_datosMouseClicked(evt);
            }
        });
        coloca_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloca_datosActionPerformed(evt);
            }
        });

        jLabel8.setText("      PUESTO");

        jLabel9.setText("    TELEFONO");

        jLabel10.setText("  DIRECCION");

        jLabel11.setText("        SEXO");

        jLabel12.setText("        NOMBRE");

        jLabel13.setText("     APELLIDOS");

        jLabel14.setText("    Nº TIENDA");

        jLabel15.setText("           DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(apellido_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tienda_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Dni_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(direccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(puesto_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alta_empleado))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(apellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tienda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dni_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(direecion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alta_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(305, 305, 305)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(alta3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dni1_eliminado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alta4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dni2_eliminado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addContainerGap())
            .addComponent(jSeparator5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consulta_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coloca_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(consulta_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consulta_tiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tienda_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dni_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direecion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alta_cliente))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tienda_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dni_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puesto_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alta_empleado))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alta3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni1_eliminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar1)
                    .addComponent(alta4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni2_eliminado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta_cliente)
                    .addComponent(consulta_empleado)
                    .addComponent(consulta_tiendas))
                .addGap(8, 8, 8)
                .addComponent(coloca_datos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar)
                    .addComponent(modificar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_clienteMouseClicked
        nombre_cliente.setText("");
    }//GEN-LAST:event_nombre_clienteMouseClicked

    private void apellido_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido_clienteMouseClicked
        apellido_cliente.setText("");
    }//GEN-LAST:event_apellido_clienteMouseClicked

    private void Dni_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dni_clienteMouseClicked
        Dni_cliente.setText("");
    }//GEN-LAST:event_Dni_clienteMouseClicked

    private void telefono_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_clienteMouseClicked
       telefono_cliente.setText("");
    }//GEN-LAST:event_telefono_clienteMouseClicked

    private void direecion_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direecion_clienteMouseClicked
        direecion_cliente.setText("");
    }//GEN-LAST:event_direecion_clienteMouseClicked

    private void sexo_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexo_clienteMouseClicked
        sexo_cliente.setText("");
    }//GEN-LAST:event_sexo_clienteMouseClicked

    private void nombre_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_empleadoMouseClicked
        nombre_empleado.setText("");
    }//GEN-LAST:event_nombre_empleadoMouseClicked

    private void apellido_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellido_empleadoMouseClicked
        apellido_empleado.setText("");
    }//GEN-LAST:event_apellido_empleadoMouseClicked

    private void Dni_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dni_empleadoMouseClicked
       Dni_empleado.setText("");
    }//GEN-LAST:event_Dni_empleadoMouseClicked

    private void telefono_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_empleadoMouseClicked
        telefono_empleado.setText("");
    }//GEN-LAST:event_telefono_empleadoMouseClicked

    private void direccion_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccion_empleadoMouseClicked
        direccion_empleado.setText("");
    }//GEN-LAST:event_direccion_empleadoMouseClicked

    private void puesto_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puesto_empleadoMouseClicked
       puesto_empleado.setText("");
    }//GEN-LAST:event_puesto_empleadoMouseClicked

    private void dni1_eliminadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dni1_eliminadoMouseClicked
        dni1_eliminado.setText("");
    }//GEN-LAST:event_dni1_eliminadoMouseClicked

    private void dni2_eliminadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dni2_eliminadoMouseClicked
        dni2_eliminado.setText("");
    }//GEN-LAST:event_dni2_eliminadoMouseClicked

    private void consulta_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_clienteActionPerformed
       try {
            gc.conect.setAutoCommit(false);

            Statement sta = gc.conect.createStatement();

            String query = "SELECT * FROM cliente ";

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();

            this.jTable2.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_consulta_clienteActionPerformed

    private void consulta_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_empleadoActionPerformed
        try {
            gc.conect.setAutoCommit(false);

            Statement sta = gc.conect.createStatement();

            String query = "SELECT * FROM empleado ";

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();

            this.jTable2.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_consulta_empleadoActionPerformed

    private void consulta_tiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_tiendasActionPerformed
        try {
            gc.conect.setAutoCommit(false);

            Statement sta = gc.conect.createStatement();

            String query = "SELECT * FROM tienda ";

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();

            this.jTable2.setModel(modelo);

            for (int i = 1; i <= numColumnas; i++) {
                modelo.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
               
    }//GEN-LAST:event_consulta_tiendasActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        gc.eliminarCliente(dni1_eliminado.getText());
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar2ActionPerformed
        gc.eliminarEmpleado(dni2_eliminado.getText());
    }//GEN-LAST:event_Eliminar2ActionPerformed

    private void alta_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_clienteActionPerformed
        gc.insertarClienteNuevo(tienda_cliente.getText(),nombre_cliente.getText(), apellido_cliente.getText(), Dni_cliente.getText(), telefono_cliente.getText(), direecion_cliente.getText(), sexo_cliente.getText());
    }//GEN-LAST:event_alta_clienteActionPerformed

    private void alta_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_empleadoActionPerformed
        gc.insertarEmpleadoNuevo(tienda_empleado.getText(),nombre_empleado.getText(), apellido_empleado.getText(), Dni_empleado.getText(), telefono_empleado.getText(), direccion_empleado.getText(), puesto_empleado.getText());
    }//GEN-LAST:event_alta_empleadoActionPerformed

    private void tienda_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tienda_clienteMouseClicked
        tienda_cliente.setText("");
    }//GEN-LAST:event_tienda_clienteMouseClicked

    private void tienda_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tienda_empleadoMouseClicked
        tienda_empleado.setText("");
    }//GEN-LAST:event_tienda_empleadoMouseClicked

    private void coloca_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coloca_datosMouseClicked
//        modificar1.setText(jTable2.getValueAt(jTable2.getSelectedRowCount()-1, 0).toString());
//        modificar2.setText(jTable2.getValueAt(jTable2.getSelectedRowCount()-1, 1).toString());
    }//GEN-LAST:event_coloca_datosMouseClicked

    private void coloca_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloca_datosActionPerformed
        modificar5.setText("");
        modificar6.setText("");
        modificar7.setText("");

        modificar1.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        modificar2.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        modificar3.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        modificar4.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        modificar5.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        modificar6.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        modificar7.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString());


    }//GEN-LAST:event_coloca_datosActionPerformed

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        gc.modificarClientedoNuevo(modificar1.getText(), modificar2.getText(), modificar3.getText(), modificar4.getText(), modificar5.getText(), modificar6.getText(), modificar7.getText());
    }//GEN-LAST:event_modificarMouseClicked
    Conexion gc = new Conexion();
    /**
     * @param args the command line arguments
     */ 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dni_cliente;
    private javax.swing.JTextField Dni_empleado;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Eliminar2;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel alta3;
    private javax.swing.JLabel alta4;
    private javax.swing.JButton alta_cliente;
    private javax.swing.JButton alta_empleado;
    private javax.swing.JTextField apellido_cliente;
    private javax.swing.JTextField apellido_empleado;
    private javax.swing.JButton coloca_datos;
    private javax.swing.JButton consulta_cliente;
    private javax.swing.JButton consulta_empleado;
    private javax.swing.JButton consulta_tiendas;
    private javax.swing.JTextField direccion_empleado;
    private javax.swing.JTextField direecion_cliente;
    private javax.swing.JTextField dni1_eliminado;
    private javax.swing.JTextField dni2_eliminado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField modificar1;
    private javax.swing.JTextField modificar2;
    private javax.swing.JTextField modificar3;
    private javax.swing.JTextField modificar4;
    private javax.swing.JTextField modificar5;
    private javax.swing.JTextField modificar6;
    private javax.swing.JTextField modificar7;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextField nombre_empleado;
    private javax.swing.JTextField puesto_empleado;
    private javax.swing.JTextField sexo_cliente;
    private javax.swing.JTextField telefono_cliente;
    private javax.swing.JTextField telefono_empleado;
    private javax.swing.JTextField tienda_cliente;
    private javax.swing.JTextField tienda_empleado;
    // End of variables declaration//GEN-END:variables
}
